# Generated by Django 5.1.5 on 2025-02-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='item_image',
            field=models.FileField(upload_to='items'),
        ),
    ]
