# Generated by Django 5.1.6 on 2025-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_alter_itemdetails_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='item_image',
            field=models.FileField(upload_to='image'),
        ),
    ]
