# Generated by Django 5.1.6 on 2025-02-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_alter_itemdetails_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetails',
            old_name='id',
            new_name='item_code',
        ),
    ]
