# Generated by Django 5.1.6 on 2025-02-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_rename_id_itemdetails_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='item_code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
