# Generated by Django 5.1.6 on 2025-02-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_alter_itemdetails_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='user',
        ),
    ]
